repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

ci:
  autofix_prs: false
  autoupdate_commit_msg: Bumps Pre-Commit Version
  autoupdate_schedule: monthly
