name: "Setup Python"
description: "Setup python, install poetry, install dependencies, cache."

inputs:
  dev:
    description: "Install developer dependencies."
    required: true
    default: "false"

  python_version:
    description: "The python version to use."
    required: true

  working_dir:
    description: "The location to run the poetry commands in"
    required: true
    default: "."

  use_cache:
    description: "Enable the usage of cache for this action"
    required: true
    default: "true"

  cache_pre-commit:
    description: "Enable caching of pre-commit dependencies"
    required: false
    default: "true"

  install_args:
    description: "Extra arguments passed to the install command"
    required: false
    default: ""

  poetry_version:
    description: "The poetry version to install (passed to pip install)"
    required: false
    default: "poetry"

outputs:
  cache-hit:
    description: "Was there a cache hit for the python cache."
    value: ${{ steps.python_cache.outputs.cache-hit }}
  python-version:
    description: "The full Python semver version used."
    value: ${{ steps.python_setup.outputs.python-version }}

runs:
  using: "composite"

  steps:
    # Checkout the code to get access to project files such as poetry and pre-commit configs
    - uses: actions/checkout@v2

    # Install python in our workflow
    - name: Setup python
      uses: actions/setup-python@v4
      id: python_setup
      with:
        python-version: ${{ inputs.python_version }}

    # Specify directories that require caching
    - name: Python Dependency Caching
      uses: actions/cache@v3
      id: python_cache
      with:
        path: |
          ~/.cache/pypoetry
          ~/.cache/py-user-base
        key: "python-${{ runner.os }}-v1.3.2-\
        ${{ steps.python_setup.outputs.python-version }}-${{ inputs.dev }}-${{ inputs.working_dir }}-${{ inputs.poetry_version }}-${{ inputs.install_args }}-\
        ${{ hashFiles(format('{0}/pyproject.toml', inputs.working_dir), format('{0}/poetry.lock', inputs.working_dir)) }}"

    # Cache pre-commit independently of other cache
    - name: Pre-commit Environment Caching
      if: ${{ inputs.cache_pre-commit }} == true
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: "precommit-${{ runner.os }}-v1.3.2-\
        ${{ steps.python_setup.outputs.python-version }}-${{ inputs.dev }}-${{ inputs.working_dir }}-${{ inputs.poetry_version }}-\
        ${{ hashFiles('./.pre-commit-config.yaml') }}"

    - name: Install Poetry
      shell: bash
      run: |
        echo "::group::Install Poetry"
        pip install ${{ inputs.poetry_version }}
        echo "::endgroup::"

    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ steps.python_cache.outputs.cache-hit }}" = "true" ]; then
          if [ "${{ inputs.use_cache }}" = "false" ]; then
            echo "Caching not enbaled, deleting cache."
            rm -rf  ~/.cache/py-user-base
            rm -rf  ~/.cache/pre-commit
          else
            echo "Cache hit, skipping install."
            exit
          fi
        fi

        echo "::group::Install Dependencies"
        cd ${{ inputs.working_dir }}

        if [ "${{ inputs.dev }}" = "true" ]; then
          python -m poetry install ${{ inputs.install_args }}
        else
          python -m poetry install ${{ inputs.install_args }} --no-dev
        fi
        echo "::endgroup::"

    - name: Configure Path
      shell: bash
      run: |
        echo "::group::Configure Path"
        cd ${{ inputs.working_dir }}
        echo "$(python -m poetry env info --path)/bin" >> $GITHUB_PATH
        echo "Added $(python -m poetry env info --path)/bin to path"
        python -m poetry -V
        echo "::endgroup::"
